Add get-version script to obtain singularity's version (#4534)
Instead of trying to pull this off using a one-liner, move the logic to
a separate script that can do error checking, etc.

In the script, change the format of the version from 3.4.1-1 to 3.4.1+1
to address #3653. Consider cases like 3.4.1-rc.1, where the "rc.1" part
does indicate a prerelease.

Signed-off-by: Marcelo E. Magallon <marcelo@sylabs.io>

diff --git a/mconfig b/mconfig
--- a/mconfig
+++ b/mconfig
@@ -48,7 +48,12 @@ cflags="$CFLAGS -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -fstack-protector
 ldflags=$LDFLAGS
 
 package_name=singularity
-package_version=`(git describe --match 'v[0-9]*' --dirty --always 2>/dev/null || cat VERSION 2>/dev/null || echo "") | sed -e "s/^v//;s/-/_/g;s/_/-/;s/_/./g"`
+package_version=`scripts/get-version`
+
+if test -z "${package_version}" ; then
+	echo "Failed to get package version. Abort."
+	exit 1
+fi
 
 with_network=1
 with_suid=1
@@ -381,8 +386,16 @@ while [ $# -ne 0 ]; do
   *) break;;
  esac
 done
-short_version="`echo "$package_version"|sed 's/-.*//'`"
-#
+
+# use a colon to provide additional version information such as a
+# release number.
+short_version="`echo "$package_version"|sed 's/:.*//'`"
+release_info="`echo "$package_version"|sed 's/^[^:]*://'`"
+if [ "${short_version}" = "${release_info}" ]; then
+	# $package_version has no colon
+	release_info=1
+fi
+
 # non-option param
 if [ $# != 0 ]; then
 	usage_args
@@ -832,12 +845,9 @@ if [ "$host" = "unix" ]; then
 	RPMSPEC=singularity.spec
 	echo "=> generating $RPMSPEC ..."
 	rm -f $sourcedir/$RPMSPEC
-	release="`echo "$package_version"|sed 's/[^-]*-//'`"
-	if [ "$short_version" = "$release" ]; then
-	    # $package_version has no dash
-	    release=1
-	fi
-	sed "s/@PACKAGE_VERSION@/$short_version/;s/@PACKAGE_RELEASE@/$release/" $sourcedir/dist/rpm/$RPMSPEC.in >$sourcedir/$RPMSPEC
+	package_rpm_version="`echo "${short_version}" | tr - .`"
+	sed "s/@PACKAGE_VERSION@/${short_version}/;s/@PACKAGE_RPM_VERSION@/${package_rpm_version}/;s/@PACKAGE_RELEASE@/${release_info}/" \
+		$sourcedir/dist/rpm/$RPMSPEC.in >$sourcedir/$RPMSPEC
 fi
 
 
