Move basic system checks to basechecks.chk.
Signed-off-by: Yannick Cote <yhcote@gmail.com>

diff --git a/core/makeit/mconfig b/core/makeit/mconfig
--- a/core/makeit/mconfig
+++ b/core/makeit/mconfig
@@ -76,6 +76,7 @@ if [ $# != 0 ]; then
 	usage_args
 	exit 2
 fi
+topdir=`dirname \`readlink mconfig\``
 sourcedir=`readlink -f .`
 mfragsdir=$sourcedir/mlocal/frags
 mchecksdir=$sourcedir/mlocal/checks
@@ -85,226 +86,14 @@ mchecksdir=$sourcedir/mlocal/checks
 #######################################################################
 # System build tool configuration and debug/verbose flags 
 #######################################################################
-echo "=> running base system checks ..."
-
-########################
-# builddir
-########################
-if [ "$builddir" = "" ]; then
-	builddir=builddir
-fi
-if [ -e $builddir -a $builddir != "." -a $builddir != ".." ]; then
-	printf "$builddir already exist, remove ? [N/y] "
-	read var
-	if [ "$var" = "y" -o "$var" = "Y" ]; then
-		rm -rf $builddir
-	else
-		echo "error: choose another build directory"
-		exit 2
-	fi
-fi
-mkdir -p $builddir
-
-
-########################
-# this product
-########################
-output=$builddir/Makefile
-
-
-########################
-# mconfig paths
-########################
-topdir=`dirname \`readlink mconfig\``
-genconfdir=`mktemp -d -p /tmp mconfig-generated-XXXXXXXXXX`
-genmk=$genconfdir/base.mk
-:>$genmk
-
-
-########################
-# host compilers
-########################
-if [ "$hstcc" = "" ]; then
-	printf " checking: host C compiler... "
-	for cc in $hstcc_opts; do
-		if $cc -E -x c /dev/null >/dev/null 2>&1; then
-			hstcc="$cc"
-			break
-		fi
-	done
-	if [ "$hstcc" != "" ]; then
-		echo $hstcc
-	else
-		echo "not found!"
-		usage
-		exit 1
-	fi
+if [ -f $topdir/basechecks.chk ]; then
+	echo "=> running base system checks ..."
+	. $topdir/basechecks.chk
 else
-	printf " checking: host C compiler... "
-	if $hstcc -E -x c /dev/null >/dev/null 2>&1; then
-		echo $hstcc
-	else
-		echo "$hstcc cannot compile test code!"
-		usage
-		exit 1
-	fi
-
-fi
-if [ "$hstcxx" = "" ]; then
-	printf " checking: host C++ compiler... "
-	for cxx in $hstcxx_opts; do
-		if $cxx -E -x c++ /dev/null >/dev/null 2>&1; then
-			hstcxx="$cxx"
-			break
-		fi
-	done
-	if [ "$hstcxx" != "" ]; then
-		echo $hstcxx
-	else
-		echo "not found!"
-		usage
-		exit 1
-	fi
-else
-	printf " checking: host C++ compiler... "
-	if $hstcxx -E -x c++ /dev/null >/dev/null 2>&1; then
-		echo $hstcxx
-	else
-		echo "$hstcxx cannot compile test code!"
-		usage
-		exit 1
-	fi
+	echo "error: file $topdir/basechecks.chk needs to be present"
+	exit 2
 fi
 
-
-########################
-# target
-########################
-if [ "$tgtcc" = "" ]; then
-	tgtcc=$hstcc
-fi
-if [ "$tgtcxx" = "" ]; then
-	tgtcxx=$hstcxx
-fi
-
-
-########################
-# target compilers
-########################
-printf " checking: target C compiler... "
-if $tgtcc -E -x c /dev/null >/dev/null 2>&1; then
-	echo $tgtcc
-else
-	echo "$tgtcc cannot compile test code!"
-	usage
-	exit 1
-fi
-printf " checking: target C++ compiler... "
-if $tgtcxx -E -x c++ /dev/null >/dev/null 2>&1; then
-	echo $tgtcxx
-else
-	echo "$tgtcxx cannot compile test code!"
-	usage
-	exit 1
-fi
-
-
-########################
-# static
-########################
-printf " checking: host compiles static binaries... "
-if ! echo "int main(int args, char *argv[]) { return 0; }" | \
-   $hstcc -x c -static -o /dev/null - >/dev/null 2>&1; then
-	hststatic=0
-	echo "no"
-else
-	echo "yes"
-fi
-printf " checking: target compiles static binaries... "
-if ! echo "int main(int args, char *argv[]) { return 0; }" | \
-   $tgtcc -x c -static -o /dev/null - >/dev/null 2>&1; then
-	tgtstatic=0
-	echo "no"
-else
-	echo "yes"
-fi
-
-
-########################
-# host os
-########################
-printf " checking: host os type... "
-host=
-if echo | $hstcc -E -dM - | grep -qs -e __unix__ -e __unix -e unix \
-	-e __APPLE__; then
-	host="unix"
-fi
-if echo | $hstcc -E -dM - | grep -qs -e _WIN32 -e _WIN64 -e __WIN32 \
-	-e __WIN64 -e __WINNT -e __WINNT__ -e __WIN32__ -e WINNT -e __WIN64__ \
-	-e WIN32 -e WIN64; then
-	host="windows"
-fi
-if [ "$host" != "" ]; then
-	echo $host
-else
-	echo "not found!"
-	usage
-	exit 1
-fi
-
-
-########################
-# target architecture
-########################
-printf " checking: target architecture... "
-tgt_arch=
-if echo | $hstcc -E -dM - | grep -qs -e __i386 -e __i386__ -e i386; then
-	tgt_arch=i386
-fi
-if echo | $hstcc -E -dM - | grep -qs -e __amd64 -e __amd64__ -e __x86_64 \
-	-e __x86_64__; then
-	tgt_arch=x86_64
-fi
-if [ "$tgt_arch" != "" ]; then
-	echo $tgt_arch
-else
-	echo "not found!"
-	usage
-	exit 1
-fi
-
-
-########################
-# wordsize
-########################
-printf " checking: architecture word size... "
-wordsize=
-if echo | $hstcc -E -dM - | grep -qs -e __i386 -e __i386__ -e i386; then
-	wordsize=32
-fi
-if echo | $hstcc -E -dM - | grep -qs -e __amd64 -e __amd64__ -e __x86_64 \
-	-e __x86_64__; then
-	wordsize=64
-fi
-if [ "$wordsize" != "" ]; then
-	echo $wordsize
-else
-	echo "not found!"
-	usage
-	exit 1
-fi
-
-
-########################
-# verbose
-########################
-echo " checking: verbose flag... $verbose"
-
-
-########################
-# debug
-########################
-echo " checking: debug flag... $debug"
 
 
 #######################################################################
@@ -520,5 +309,6 @@ else
 	echo "    - debug: no"
 fi
 
-echo "=> $builddir/Makefile ready:"
-echo " cd $builddir; make"
+echo "=> $builddir/Makefile ready, try:"
+echo "   $ cd $builddir"
+echo "   $ make"
