Fix up abort messages

diff --git a/libexec/functions b/libexec/functions
--- a/libexec/functions
+++ b/libexec/functions
@@ -55,6 +55,11 @@ message() {
             printf "ERROR: $MESSAGE" "$@" 1>&2
             tput -Txterm sgr0 2>/dev/null
         ;;
+        a|ABORT)
+            tput -Txterm setaf 1 2>/dev/null
+            printf "ABORT: $MESSAGE" "$@" 1>&2
+            tput -Txterm sgr0 2>/dev/null
+        ;;
         w|warn|warning|W|WARN|WARNING)
             tput -Txterm setaf 3 2>/dev/null
             printf "WARNING: $MESSAGE" "$@" 1>&2
@@ -151,7 +156,7 @@ ABORT() {
     if [ -z "$RETVAL" ]; then
         RETVAL=1
     fi
-    message ERROR "Aborting with RETVAL=$RETVAL\n"
+    message ABORT "Aborting with RETVAL=$RETVAL\n"
     exit $RETVAL
 }
 
