Output cleanups and support warning message (level 1)

diff --git a/libexec/functions b/libexec/functions
--- a/libexec/functions
+++ b/libexec/functions
@@ -46,13 +46,17 @@ message() {
     shift
     if [ "$LEVEL" -eq "0" ]; then
         tput -Txterm setaf 1 2>/dev/null
-        printf "$MESSAGE" "$@" 1>&2
+        printf "ERROR: $MESSAGE" "$@" 1>&2
+        tput -Txterm sgr0 2>/dev/null
+    elif [ "$LEVEL" -eq "1" ]; then
+        tput -Txterm setaf 3 2>/dev/null
+        printf "WARN: $MESSAGE" "$@" 1>&2
         tput -Txterm sgr0 2>/dev/null
     elif [ "$LEVEL" -le "$MESSAGELEVEL" ]; then
-        if [ "$LEVEL" -eq "1" ]; then
+        if [ "$LEVEL" -eq "2" ]; then
             printf "$MESSAGE" "$@"
         else
-            tput -Txterm dim 2>/dev/null
+            tput -Txterm setaf 7 2>/dev/null
             printf "${GRAY}$MESSAGE${NORMAL}" "$@"
             tput -Txterm sgr0 2>/dev/null
         fi
@@ -76,7 +80,7 @@ get_section_from_conf() {
     FILE="$2"
     TOGGLE=""
     if [ ! -f "$FILE" ]; then
-        message 0 "ERROR: File not found ($FILE)\n"
+        message 0 "File not found ($FILE)\n"
         exit 1
     fi
     if ! grep -q "^%$SECTION" "$FILE"; then
@@ -114,13 +118,13 @@ check_pattern() {
 }
 
 cmd() {
-    message 1 " + %-68.68s" "$*"
+    message 3 " + %-68.68s" "$*"
     "$@" >/dev/null 2>&1
     RETVAL=$?
     if [ $RETVAL -eq 0 ]; then
-        message 2 "${GREEN}OK${NORMAL}\n"
+        message 3 "OK\n"
     else
-        message 2 "${RED}ERROR${NORMAL}\n"
+        message 3 "ERROR\n"
     fi
     return $RETVAL
 }
@@ -130,21 +134,21 @@ stest() {
     ERROR="$1"
     TMPFILE=`mktemp`
     shift
-    message 1 " + %-60.60s " "$*"
+    message 3 " + %-60.60s " "$*"
     "$@" >$TMPFILE 2>&1
     CODE="$?"
     if [ "$ERROR" = "0" -a "$CODE" != "0" ]; then
-        message 1 "%10s ${RED}ERROR${NORMAL}\n" "(retval=$CODE)"
+        message 3 "%10s ERROR\n" "(retval=$CODE)"
         tail "$TMPFILE"
         echo "Full output in: $TMPFILE"
         exit 1
     elif [ "$ERROR" != "0" -a "$CODE" = "0" ]; then
-        message 1 "%10s ${RED}ERROR${NORMAL}\n" "(retval=$CODE)"
+        message 3 "%10s ERROR\n" "(retval=$CODE)"
         tail "$TMPFILE"
         echo "Full output in: $TMPFILE"
         exit 1
     else
-        message 1 "%10s ${GREEN}OK${NORMAL}\n" "(retval=$CODE)"
+        message 3 "%10s OK\n" "(retval=$CODE)"
     fi
     rm -f "$TMPFILE"
 }
@@ -153,13 +157,13 @@ stest() {
 load_mod() {
     MOD="$1"
     if [ -z "$libexecdir" ]; then
-        message 0 "ERROR: libexecdir not defined, are you running this from within Singularity?\n"
+        message 0 "libexecdir not defined, are you running this from within Singularity?\n"
         exit 1
     fi
     if [ -f "$libexecdir/singularity/mods/$MOD.smod" ]; then
         . "$libexecdir/singularity/mods/$MOD.smod"
     else
-        message 0 "ERROR: Could not load Singularity module: $MOD\n"
+        message 0 "Could not load Singularity module: $MOD\n"
         exit 1
     fi
 }
