Bootstrap format v2 coming along

diff --git a/libexec/functions b/libexec/functions
--- a/libexec/functions
+++ b/libexec/functions
@@ -69,7 +69,7 @@ message() {
 singularity_key_get() {
     KEY="${1:-}"
     FILE="${2:-}"
-    if OUT=`egrep -i "^$KEY:\s*" $FILE`; then
+    if OUT=`egrep -i "^$KEY:" $FILE`; then
         echo "$OUT" | head -n 1 | sed -e "s@^$KEY:\s*@@i"
         return 0
     fi
@@ -80,7 +80,7 @@ singularity_key_get() {
 singularity_keys_get() {
     KEY="${1:-}"
     FILE="${2:-}"
-    egrep -i "^$KEY:\s*" "$FILE" | while read i; do
+    egrep -i "^$KEY:" "$FILE" | while read i; do
         echo "$i" | sed -e "s@^$KEY:\s*@@i"
     done | tr '\n' ' '
     echo
@@ -96,9 +96,23 @@ singularity_section_exists() {
         message ERROR "File not found ($FILE)\n"
         exit 1
     fi
-    if ! grep -q "^%$SECTION\$" "$FILE"; then
+    if ! egrep -i -q -- "^%$SECTION\W*" "$FILE"; then
         return 1
     fi
+
+    return 0
+}
+
+singularity_section_args() {
+    SECTION="${1:-}"
+    FILE="${2:-}"
+    TOGGLE=""
+    if [ ! -f "$FILE" ]; then
+        message ERROR "File not found ($FILE)\n"
+        exit 1
+    fi
+
+    egrep -i -- "^%$SECTION\W*" "$FILE" | sed -e "s@%$SECTION\s*@@i"
 
     return 0
 }
@@ -111,7 +125,7 @@ singularity_section_get() {
         message ERROR "File not found ($FILE)\n"
         exit 1
     fi
-    if ! grep -q "^%$SECTION\$" "$FILE"; then
+    if ! grep -q "^%$SECTION\W*" "$FILE"; then
         return 1
     fi
     cat "$FILE" | while read line; do
@@ -122,7 +136,7 @@ singularity_section_get() {
             fi
             /bin/echo "$line"
         else
-            if /bin/echo "$line" | grep -q "^%$SECTION\$"; then
+            if /bin/echo "$line" | egrep -i -q -- "^%$SECTION\W*"; then
                 TOGGLE=1
             fi
         fi
