adding support for nvidia-container-cli if installed

diff --git a/libexec/functions b/libexec/functions
--- a/libexec/functions
+++ b/libexec/functions
@@ -453,6 +453,66 @@ is_tar() {
 }
 
 
+bind_nvidia_files() {
+# either use nvidia-container-cli or nvliblist.conf to find nvidia libs and
+# binaries for binding at runtime with --nv 
+    if ! SINGULARITY_NVLIBLIST=`mktemp "${TMPDIR:-/tmp}"/.singularity-nvliblist.XXXXXXXX`; then
+        message ERROR "Failed to create temporary nvliblist file.\n"
+        ABORT 255
+    fi
+
+    # try to use nvidia-container-cli if installed and functional
+    if singularity_which nvidia-container-cli > /dev/null 2>&1 && SINGULARITY_NV_FILES=`nvidia-container-cli list -cguv`; then
+        # bins should have full paths
+        SINGULARITY_NVBINLIST=`echo "$SINGULARITY_NV_FILES" | grep -Ev "\.so"`
+        # libs should just be basenames ending in ".so"
+        for i in `echo "$SINGULARITY_NV_FILES" | grep -E "\.so"`; do
+            basename "$i" | awk -F "\.so" '{print $1 ".so"}' >> "$SINGULARITY_NVLIBLIST"
+        done
+
+    else # fall back to nvliblist.conf
+        message 2 "nvidia-container-cli not installed or returning error\n"
+        message 2 "falling back to $SINGULARITY_sysconfdir/singularity/nvliblist.conf\n"
+        # strip comments and spaces and bins do NOT end in .so
+        SINGULARITY_NVBINLIST=`cat $SINGULARITY_sysconfdir"/singularity/nvliblist.conf" | grep -Ev "^#|^\s*$" | grep -vE "\.so$"`
+        # strip comments and spaces and libs DO end in .so
+        cat "$SINGULARITY_sysconfdir/singularity/nvliblist.conf" | grep -Ev "^#|^\s*$" | grep -E "\.so$" > $SINGULARITY_NVLIBLIST
+    fi
+
+    # first deal with libs (pattern match from ld.so cache)
+    for i in $(ldconfig -p | grep -f "${SINGULARITY_NVLIBLIST}"); do
+        if [ -f "$i" ]; then
+            message 2 "Found NV library: $i\n"
+            SINGULARITY_CONTAINLIBS="${SINGULARITY_CONTAINLIBS:-},$i"
+        fi
+    done
+    rm $SINGULARITY_NVLIBLIST
+
+    # then deal with bins (should have full path specified)
+    for SINGULARITY_NVBIN in $SINGULARITY_NVBINLIST; do
+        if [ -f "$SINGULARITY_NVBIN" ]; then
+            message 2 "Found NV binary: $SINGULARITY_NVBIN\n"
+            SINGULARITY_BINDPATH="${SINGULARITY_BINDPATH:-},${SINGULARITY_NVBIN}"
+        fi
+    done
+
+    # in case we couldn't find files, warn the user. otherwise export variables
+    if [ -z "${SINGULARITY_CONTAINLIBS:-}" ]; then
+         message WARNING "Could not find any NVIDIA libraries on this host!\n";
+         message WARNING "You may need to edit $SINGULARITY_sysconfdir/singularity/nvliblist.conf\n"
+    else
+        export SINGULARITY_CONTAINLIBS
+    fi
+
+    if [ -z "${SINGULARITY_NVBIN:-}" ]; then
+         message WARNING "Could not find any NVIDIA binaries on this host!\n";
+         message WARNING "You may need to edit $SINGULARITY_sysconfdir/singularity/nvliblist.conf\n"
+    else
+        export SINGULARITY_BINDPATH
+    fi
+}
+
+
 ##############################################################################
 # CHECKS
 ##############################################################################
