More updates for the new architecture
I think build is pretty much done at this point. Still testing though
and moving on to the C code.

diff --git a/libexec/sapp_build b/libexec/sapp_build
--- a/libexec/sapp_build
+++ b/libexec/sapp_build
@@ -24,6 +24,8 @@ fi
 
 
 SAPPSPEC="$1"
+SAPPFILE="$2"
+export SAPPSPEC SAPPFILE
 
 if [ -z "$SAPPSPEC" ]; then
     message 1 "SAPP specfile not given"
@@ -37,272 +39,68 @@ fi
 
 
 NAME=`get_key_from_conf "Name" $SAPPSPEC`
+SUMMARY=`get_key_from_conf "Summary" $SAPPSPEC`
+SAPPNAME=`echo "$NAME" | sed -e 's@ @_@g'`
 TMPDIR=`mktemp -d /tmp/.singularity.XXXXXXX`
-SAPPFILENAME=`echo "$NAME" | sed -e 's@ @_@g'`
-SAPPFILE="$SAPPFILENAME.sapp"
-
-export TMPDIR SAPPSPEC SAPPFILE
+export TMPDIR
 
 message 1 "Building '$NAME'"
+
 message 2 "Working directory: $TMPDIR"
 
-for i in sapp_build_base sapp_build_deps_* sapp_build_archive; do
+
+if [ -n "$SAPPFILE" ]; then
+    if [ -d "$SAPPFILE" ]; then
+        SAPPFILE=`echo "$SAPPFILE/$SAPPNAME.sapp" | sed -e 's@//@/@g'`
+    else
+        DIRNAME=`dirname "$SAPPFILE"`
+        if [ ! -d "$DIRNAME" ]; then
+            if ! mkdir -p "$DIRNAME"; then
+                message 1 "Could not create output directory"
+                exit 1
+            fi
+        fi
+    fi
+else
+    SAPPFILE="$SAPPNAME.sapp"
+fi
+
+if ! touch "$SAPPFILE" 2>/dev/null; then
+    echo "Could not create $SAPPFILE"
+    exit 1
+fi
+
+
+
+echo "#!/bin/env singularity run" > $SAPPFILE
+echo "Payload: 5" >> $SAPPFILE
+echo "Name: $NAME" >> $SAPPFILE
+echo "Summary: $SUMMARY" >> $SAPPFILE
+
+for i in sapp_build_base sapp_build_deps_libs sapp_build_archive; do
     if [ -f "$libexecdir/singularity/$i" ]; then
         message 3 "Running: $libexecdir/singularity/$i"
         sh "$libexecdir/singularity/$i"
         EXITCODE="$?"
-        if [ "$EXITCODE" -ne 0 ]; then
+        if [ "$EXITCODE" -ne "0" ]; then
             message 1 "Error thrown from module: $i"
             message 2 "Left tmpdir at $TMPDIR"
+            rm -f $SAPPFILE
             exit $EXITCODE
         fi
     else
-        message 1 "Error locating module: $i"
+        message 1 "Error locating module: $libexecdir/singularity/$i"
         message 2 "Left tmpdir at $TMPDIR"
+        rm -f $SAPPFILE
         exit 1
     fi
 
 done
 
-rm -rf $TMPDIR
-
-exit $RETVAL
-
-
-
-
-
-RETVAL=0
-TMPDIR=`mktemp -d /tmp/singularity-build.XXXXXXXX`
-INCLUDEBIN="/bin/sh"
-LIBSUFFIX=`uname -m | grep -qv x86_64 || echo 64`
-
-
-includefile() {
-    for file in $@; do
-        DIRNAME=`dirname $file`
-        if [ ! -d "$TMPDIR/$DIRNAME" ]; then
-            mkdir -p "$TMPDIR/$DIRNAME"
-        fi
-        if [ ! -f "$TMPDIR/$file" ]; then
-            echo "including file:        $file"
-            cp -L "$file" "$TMPDIR/$file"
-        fi
-    done
-}
-
-includebin() {
-    for file in $@; do
-        DIRNAME=`dirname $file`
-        if [ ! -d "$TMPDIR/$DIRNAME" ]; then
-            mkdir -p "$TMPDIR/$DIRNAME"
-        fi
-        if [ ! -f "$TMPDIR/$file" ]; then
-            echo "including program:     $file"
-            cp -L "$file" "$TMPDIR/$file"
-            ldd $file | sed -e 's@ @\n@g' | while read i; do
-                if [ -f "$i" ]; then
-                    echo " ->dependency:         $i"
-                    if [ ! -d "$TMPDIR/lib$LIBSUFFIX" ]; then
-                        mkdir -p "$TMPDIR/lib$LIBSUFFIX"
-                    fi
-                    if [ ! -f "$TMPDIR/lib$LIBSUFFIX/$BASENAME" ]; then
-                        cp -L "$i" "$TMPDIR/lib$LIBSUFFIX/$BASENAME"
-                    fi
-                fi
-            done
-        fi
-    done
-}
-
-
-cleanup() {
+if [ -z "$DEBUG" ]; then
     rm -rf $TMPDIR
-}
-
-
-key_from_conf() {
-    KEY="$1"
-    FILE="$2"
-    grep "^$KEY: " $FILE | while read i; do
-        echo "$i" | sed -e "s@^$KEY: @@"
-    done
-}
-
-
-usage() {
-    echo "USAGE: $0 (options) [config] (output file)"
-    echo
-    echo "CONFIG:"
-    echo "  The path to the configruation file spec that defines the application"
-    echo "  stack you wish to include in the singularity package."
-    echo
-    echo "ARGUMENTS:"
-    echo "  -h      Print usage summary"
-    echo
-}
-
-
-while getopts ":c:" opt; do
-    case $opt in
-        h)
-            usage
-            exit
-        ;;
-        \?)
-            echo "Invalid option -$OPTARG" >&2
-            exit 1
-        ;;
-        :)
-            echo "Option -$OPTARG requires an argument." >&2
-            exit 1;
-        ;;
-    esac
-done
-
-CONFIG=$1
-shift
-OUTPUT=$1
-shift
-
-if [ -z "$CONFIG" ]; then
-    usage
-    exit 1
-fi
-
-
-PROGRAM=`parseconf program $CONFIG`
-FILE=`parseconf file $CONFIG`
-RUNFILE=`parseconf run $CONFIG`
-NAME=`parseconf name $CONFIG`
-
-
-if [ -z "$PROGRAM" ]; then
-    echo "PROGRAM is undefined!"
-    exit 1
-fi
-
-
-if [ -z "$OUTPUT" ]; then
-    if [ -z "$NAME" ]; then
-        NAME=`basename $CONFIG`
-    fi
-    OUTPUT="$NAME.sapp"
-fi
-
-for i in $PROGRAM; do
-    PROGRAM_BIN=`which $i 2>/dev/null`
-    includebin $PROGRAM_BIN
-#    includelddeps $PROGRAM_BIN
-    if [ -z "$PROGFIRST" ]; then
-        PROGFIRST="$i"
-    fi
-done 
-
-for i in $FILE; do
-    includefile $i
-done
-
-
-includebin $INCLUDEBIN
-
-includefile /etc/ld.so.cache
-includefile /etc/ld.so.conf
-includefile /etc/ld.so.conf.d/*
-includefile /dev/null
-
-echo "#!/bin/sh" > $TMPDIR/run
-echo "PATH=/bin:$PATH" >> $TMPDIR/run
-echo "export PATH" >> $TMPDIR/run
-if [ -n "$RUNFILE" ]; then
-    echo "$RUNFILE" >> $TMPDIR/run
 else
-    echo "$PROGFIRST \$@" >> $TMPDIR/run
+    message 5 "working directory at: $TMPDIR"
 fi
-chmod +x $TMPDIR/run
-
-
-if $libexecdir/singularity/sapp_archive $TMPDIR $OUTPUT; then
-    echo "WROTE: $OUTPUT"
-    chmod +x $OUTPUT
-    cleanup
-else
-    RETVAL=1
-fi
-
 
 exit $RETVAL
-
-
-
-
-
-
-
-
-
-
-
-
-#################
-
-DIRECTORY=$1
-SAPPFILE=$2
-
-if [ -z "$SAPPFILE" -o -z "$DIRECTORY" ]; then
-    echo "USAGE: [SAPP DIRECTORY] [SAPP FILE]"
-    exit 1
-fi
-
-if [ ! -d "$DIRECTORY" ]; then
-    echo "ERROR: Could not find SAPP directory: $DIRECTORY"
-    exit 1
-fi
-
-if [ ! -x "$DIRECTORY/run" ]; then
-    echo "ERROR: Directory is not correct format: $DIRECTORY"
-    exit 1
-fi
-
-if [ ! -d "$DIRECTORY" ]; then
-    if ! mkdir -p "$DIRECTORY"; then
-        echo "ERROR: Could not create target directory: $DIRECTORY"
-        exit 1
-    fi
-fi
-
-
-check_valid() {
-    STRING=$1
-    PATTERN=$2
-    case $STRING in
-        $PATTERN)
-            true
-        ;;
-        *)
-            echo "bad"
-            return 1
-        ;;
-    esac
-    return 0
-}
-
-
-# TODO Check for root here...
-
-
-# Create SAPP file header
-echo "#!/bin/env singularity" > $SAPPFILE
-echo "PAYLOAD=7" >> $SAPPFILE
-echo "DATE='`date +%Y.%m.%d`'" >> $SAPPFILE
-echo "USER='`id -un`'" >> $SAPPFILE
-echo "BUILDHOST='`hostname`'" >> $SAPPFILE
-if [ -f "/etc/redhat-release" ]; then
-    echo "OSVERSION='`cat /etc/redhat-release`'" >> $SAPPFILE
-elif [ -f "/etc/debian-release" ]; then
-    echo "OSVERSION='`cat /etc/debian-release`'" >> $SAPPFILE
-fi
-
-(cd $DIRECTORY; find . | cpio -o --quiet -H newc ) | gzip -c9 >> $SAPPFILE
-
-exit 0
