Run e2e tests based on changes.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -155,25 +155,48 @@ jobs:
       - name: Get git tags
         run: git fetch --prune --unshallow --tags
 
+      - name: Check changes
+        env:
+          PROJECT_REPOSITORY: ${{ github.repository }}
+          PROJECT_PR_NUMBER: ${{ github.event.pull_request.number }}
+        run: |
+          rc=0
+          ./scripts/should-e2e-run "${PROJECT_REPOSITORY}" "${GITHUB_REF##*/}" "${PROJECT_PR_NUMBER}" || rc=$?
+          case $rc in
+            0)
+              echo "Verifying critical changes"
+              echo "run_tests=true" >> $GITHUB_ENV ;;
+            1)
+              echo "No critical changes, skipping tests" ;;
+            *)
+              echo "E: ./scripts/should-e2e-run returned with exit code $rc. Abort."
+              exit $rc ;;
+          esac
+
       - name: Setup Go
+        if: env.run_tests
         uses: actions/setup-go@v2
         with:
           go-version: 1.14.15
 
       - name: Fetch deps
+        if: env.run_tests
         run: sudo apt-get install -y build-essential squashfs-tools libseccomp-dev cryptsetup
 
       - name: Build and install Singularity
+        if: env.run_tests
         run: |
           ./mconfig -v -p /usr/local
           make -C ./builddir all && sudo make -C ./builddir install
 
       - name: Run E2E tests
+        if: env.run_tests
         env:
           E2E_PARALLEL: 8
         run: make -C ./builddir e2e-test
 
       - name: Upload artifacts
+        if: env.run_tests
         uses: actions/upload-artifact@v2
         with:
           name: e2e-artifact
